name: secure_lite_storage
description: "A simple, secure, fast, light and synchronous key-value storage written."
version: 1.0.0
homepage: ''

environment:
  sdk: '^3.7.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider:
  cryptography:

dev_dependencies:
  flutter_lints: