name: secure_lite_storage
description: "A simple, secure, fast, light and synchronous key-value storage written."
version: 1.0.0
homepage: https://github.com/ArZHa03/secure_lite_storage

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.1.5
  cryptography: ^2.7.0

dev_dependencies:
  flutter_lints: ^5.0.0